refly-ai/refly

README.md
README_CN.md

- Added cover image to the top of both English and Chinese README files
- Removed duplicate cover image from the description section
- Enhanced visual consistency and hierarchy across language versions
> [!Tip]
> Please review the checklist …

docs: Update cover image placement in README files

---

README_CN.md

docs(readme): Update local development access URL in Chinese README

---

.github/workflows/docker-deploy.yml
apps/api/Dockerfile
apps/api/package.json
apps/api/src/scripts/sync-db-schema.ts
deploy/docker/docker-compose.yml

Enable automatic schema migration when starting api container.
> [!Tip]

fix(docker): enable auto schema migration for api image

---

apps/web/src/components/landing-page-partials/HeroHome.tsx
apps/web/src/components/layout/sider.tsx
packages/ai-workspace-common/src/components/settings/subscribe-modal/priceContent.tsx

- Restore Product Hunt badge in landing page and sider layout
- Add null-safe array mapping in PriceContent component
- Ensure consistent rendering of features and capabilities
> [!Tip]
> Please review the checklist below before submitting …

feat(ui): Uncomment Product Hunt badge in HeroHome and Sider components

---

.github/workflows/build-es-image.yml
.github/workflows/build-middleware-image.yml
README.md
README_CN.md
apps/api/src/common/elasticsearch.service.ts
deploy/docker/docker-compose.middleware.yml
deploy/docker/docker-compose.yml
deploy/docker/qdrant/Dockerfile

- Add `healthcheck` to all middleware containers
- Only start `refly_api` when all middleware containers are **healthy**
- Build custom qdrant image (with `curl` installed)

feat(docker): add healthcheck to middleware container for stable bootstrap

---

apps/web/src/components/landing-page-partials/HeroHome.tsx
apps/web/src/components/layout/sider.tsx

- Comment out Product Hunt badge in landing page and sider layout
- Maintain clean and minimal UI design
- Preserve commented-out code for potential future use
> [!Tip]

chore(ui): Remove Product Hunt badge from HeroHome and Sider components

---

apps/web/src/components/landing-page-partials/HeroHome.tsx
packages/ai-workspace-common/src/components/settings/subscribe-modal/priceContent.tsx
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

feat(ui): Update pricing and model references with DeepSeek R1

---

packages/ai-workspace-common/src/components/canvas/nodes/skill.tsx
packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-text.tsx

fix(web): infinite loop error when importing text

---

apps/api/src/subscription/subscription.service.ts

Check for subscriptionId match before reset user to free plan in `cancelSubscription`.
> [!Tip]

fix(api): check for matching subscriptionId when cancelling subscriptions

---

apps/web/src/components/landing-page-partials/HeroHome.tsx
packages/ai-workspace-common/src/components/workspace/resource-list/index.tsx
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

feat(landing): Update Chrome extension web clipper launch messaging

---

packages/utils/src/parse.ts

feat(utils): Add LaTeX delimiter conversion for markdown parsing

---

apps/api/prisma/schema.prisma
apps/api/src/app.module.ts
apps/api/src/auth/auth.service.ts
apps/api/src/canvas/canvas.service.ts
apps/api/src/config/app.config.ts
apps/api/src/knowledge/knowledge.service.ts
apps/api/src/knowledge/parsers/base.ts
apps/api/src/knowledge/parsers/jina.parser.ts
apps/api/src/misc/misc.controller.ts
apps/api/src/misc/misc.dto.ts
apps/api/src/misc/misc.module.ts
apps/api/src/misc/misc.processor.ts
apps/api/src/misc/misc.service.ts
apps/api/src/search/search.service.ts
packages/ai-workspace-common/src/requests/types.gen.ts
packages/openapi-schema/schema.yml
packages/openapi-schema/src/schemas.gen.ts
packages/openapi-schema/src/types.gen.ts

- Support visibility control for uploaded files (private by default)
- Support automatic image dump (to Refly storage) from parsed markdown content
- Fix Jina parser issues

feat: support file visibility control

---

package.json
packages/ai-workspace-common/package.json
packages/ai-workspace-common/src/components/canvas/nodes/shared/content-preview.tsx
packages/ai-workspace-common/src/components/markdown/index.tsx
packages/ai-workspace-common/src/components/markdown/plugins/code/render.tsx
packages/ai-workspace-common/src/components/markdown/plugins/mermaid/index.ts
packages/ai-workspace-common/src/components/markdown/plugins/mermaid/render.tsx
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts
pnpm-lock.yaml

- Integrate Mermaid library for rendering diagrams in markdown code blocks
- Add dynamic rendering with error handling and caching
- Implement performance optimizations with memoization
- Update i18n translations for Mermaid-related messages
- Add dependencies for Mermaid and lodash-es
> [!Tip]
| …

feat(markdown): Add Mermaid diagram rendering support

---

apps/api/src/misc/misc.service.ts

- Preserve GIF format during image resizing
- Update content type and file extension handling for GIFs
- Maintain original image scaling logic for all image types
> [!Tip]

feat(api): Add GIF support in image processing

---

packages/ai-workspace-common/src/components/canvas/node-preview/node-preview-header.tsx

> [!Tip]
| ![CleanShot 2025-02-16 at 22 37 05@2x](https://github.com/user-attachments/assets/57e9a9b8-d22a-47f3-8fa4-95e9b735bf7a) | ![CleanShot 2025-02-16 at 22 38 13@2x](https://github.com/user-attachments/assets/a7ea2fd2-94be-46f4-904f-5607d9079127)   |
> …

feat(node-preview-header): add minimized2 icon for node-preview-header

---

.github/workflows/e2e.yml
apps/api/src/common/minio.service.ts
package.json
pnpm-lock.yaml

fix(api): make minio initialization compatible with cloudflare R2

---

packages/ai-workspace-common/src/components/import-resource/index.tsx

fix(web): make import resource modal vertically centered

---

packages/ai-workspace-common/src/components/canvas/constants.ts
packages/ai-workspace-common/src/components/canvas/edges/custom-edge.tsx
packages/ai-workspace-common/src/components/canvas/index.tsx
packages/ai-workspace-common/src/components/canvas/nodes/document.tsx
packages/ai-workspace-common/src/components/canvas/nodes/image.tsx
packages/ai-workspace-common/src/components/canvas/nodes/index.ts
packages/ai-workspace-common/src/components/canvas/nodes/memo/memo.tsx
packages/ai-workspace-common/src/components/canvas/nodes/resource.tsx
packages/ai-workspace-common/src/components/canvas/nodes/shared/custom-handle.tsx
packages/ai-workspace-common/src/components/canvas/nodes/shared/node-resizer.tsx
packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
packages/ai-workspace-common/src/components/canvas/nodes/skill.tsx

feat: support custom edge connections for canvas nodes

---

packages/ai-workspace-common/src/components/canvas/edges/custom-edge.tsx

- Add double-click event to edit edge label
- Implement dynamic edge styling for selected state
- Improve label editing behavior and visibility
- Optimize edge label rendering and interaction
> [!Tip] …

feat(canvas): enhance custom edge interaction and styling

---

apps/api/package.json
apps/api/src/canvas/canvas-title-generator.ts
apps/api/src/canvas/canvas.service.ts
packages/skill-template/src/index.ts
pnpm-lock.yaml

- Add comprehensive canvas title generation with structured output
- Integrate Zod schema for consistent title generation
- Implement multiple fallback strategies for robust title extraction
- Support various content types (questions, documents, resources)
- Enhance title generation with advanced JSON parsing and repair techniques
- Add detailed logging and error handling for title generation process
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull- …

feat(canvas): implement advanced AI-powered canvas title generation

---

apps/api/src/subscription/subscription.service.ts

- Add robust customer ID retrieval and creation logic
- Search for existing Stripe customers by email
- Update user records with found or created customer IDs
- Enhance error handling in checkout and portal session creation
- Ensure consistent customer ID management across subscription flows
> [!Tip]

fix(subscription): improve Stripe customer handling and session creation

---

apps/api/src/canvas/canvas.service.ts

fix(api): add null check and user context retrieval in canvas service

---

CONTRIBUTING_CN.md

This PR adds Chinese translation of the CONTRIBUTING.md file to improve accessibility for Chinese-speaking contributors. The new file CONTRIBUTING_CN.md provides a complete translation of the original contribution guidelines, maintaining all technical terms and code blocks in English while translating the explanatory text. This addition also fulfills the reference in README_CN.md which previously mentioned this file but it was missing.

fix: CONTRIBUTING_CN.md missing

---

apps/web/src/components/landing-page-partials/Header.tsx
apps/web/src/components/landing-page-partials/HeroHome.tsx
apps/web/src/components/landing-page-partials/header.scss
apps/web/src/pages/home/index.scss
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

- Add community dropdown with Discord and WeChat options
- Implement language selector with UILocaleList component
- Update header layout and styling for better responsiveness
- Adjust header padding and max-width for improved design
- Update i18n translations for new header elements
> [!Tip]
| …

feat(landing-page): enhance header navigation and internationalization

---

apps/api/prisma/schema.prisma
apps/api/src/subscription/subscription.dto.ts
apps/api/src/subscription/subscription.service.ts

Support changing subscription for users.
> [!Tip]

feat: support changing subscription

---

packages/ai-workspace-common/src/components/canvas/node-action-menu/index.tsx

- Modify preview menu item rendering to include image nodes
- Extend preview menu item condition to support image type nodes
> [!Tip]

feat(node-action-menu): add image node preview support

---

packages/i18n/src/en-US/ui.ts

- Add new slogan text for the landing page
- Enhance descriptive messaging for Refly's value proposition
> [!Tip]

feat(i18n): update landing page slogan for en-US translations

---

apps/web/src/components/landing-page-partials/Header.tsx
apps/web/src/components/landing-page-partials/frequently-asked-questions.tsx
packages/ai-workspace-common/src/components/settings/subscribe-modal/priceContent.tsx
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

- Expanded the FAQ section to include additional questions and updated answers for clarity and accuracy.
- Simplified the header label for the pricing tab by removing the badge component.
- Revised pricing details for subscription plans, including updated model names and adjusted pricing values for monthly and yearly intervals.
- Cleaned up translation files to reflect the latest changes in both English and Chinese.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue …

feat: update FAQ section, header label, and pricing details

---

apps/api/src/subscription/subscription.service.ts

- Fix incorrect usage tracking for free tier models
- Fix throwing errors for missing subscription plans
> [!Tip]

fix: subscription related issues

---

apps/api/prisma/schema.prisma
apps/api/src/action/action.service.ts
apps/api/src/canvas/canvas.service.ts
apps/api/src/knowledge/parsers/marker.parser.ts
apps/api/src/skill/skill.service.ts
apps/api/src/subscription/subscription.service.ts
packages/ai-workspace-common/src/components/canvas-template/create-template-modal.tsx
packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/action-container.tsx
packages/ai-workspace-common/src/components/canvas/top-toolbar/canvas-rename.tsx
packages/ai-workspace-common/src/components/canvas/top-toolbar/share-settings.tsx
packages/ai-workspace-common/src/components/document/index.tsx
packages/ai-workspace-common/src/components/search/index.tsx
packages/ai-workspace-common/src/hooks/canvas/use-create-document.ts
packages/ai-workspace-common/src/hooks/use-duplicate-canvas.ts
packages/ai-workspace-common/src/modules/artifacts/code-runner/code-viewer.tsx

fix: canvas duplication related issues

---

packages/ai-workspace-common/src/requests/types.gen.ts
packages/openapi-schema/schema.yml
packages/openapi-schema/src/schemas.gen.ts
packages/openapi-schema/src/types.gen.ts
packages/skill-template/src/scheduler/utils/context.ts
packages/skill-template/src/scheduler/utils/message.ts
packages/skill-template/src/scheduler/utils/truncator.ts
packages/skill-template/src/skills/code-artifacts.ts
packages/skill-template/src/skills/common-qna.ts
packages/skill-template/src/skills/custom-prompt.ts
packages/skill-template/src/skills/edit-doc.ts
packages/skill-template/src/skills/generate-doc.ts
packages/skill-template/src/skills/library-search.ts
packages/skill-template/src/skills/rewrite-doc.ts
packages/skill-template/src/skills/web-search.ts

- Introduced a new property `contextCaching` to the `ModelCapabilities` type and corresponding OpenAPI schema, allowing models to indicate support for context caching.
- Updated relevant components to utilize the new `modelInfo` property for context caching decisions in message handling.
- Enhanced message processing to apply context caching based on model capabilities, improving efficiency in message management.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#li …

feat(api): add context caching support to model capabilities

---

apps/api/src/action/action.service.ts
apps/api/src/canvas/canvas.service.ts

fix: action result duplication issues

---

apps/api/src/subscription/subscription.service.ts
packages/utils/src/editor/to_markdown.ts

fix: table render issues and long transaction

---

apps/api/src/misc/misc.service.ts
apps/api/src/share/share.service.ts
apps/api/src/template/template.module.ts
apps/api/src/template/template.service.ts
packages/ai-workspace-common/src/components/canvas-template/create-template-modal.tsx
packages/ai-workspace-common/src/components/canvas/top-toolbar/share-settings.tsx
packages/ai-workspace-common/src/hooks/use-export-canvas-as-image.ts
packages/ai-workspace-common/src/requests/types.gen.ts
packages/openapi-schema/schema.yml
packages/openapi-schema/src/schemas.gen.ts
packages/openapi-schema/src/types.gen.ts

feat: optimize canvas cover upload

---

apps/web/src/components/landing-page-partials/use-cases-gallery/data.ts

- Replaced the cover image for a specific use case in the useCasesData array, ensuring the latest visual is displayed.
- Ensured compliance with code style rules, including the use of single quotes for string literals.
> [!Tip]
> Please review …

fix(use-cases-gallery): update cover image for a specific use case

---

packages/ai-workspace-common/src/modules/artifacts/code-runner/code-viewer.tsx

- Updated the upload function in the code viewer to include a default visibility setting of 'public' for uploaded files, ensuring consistent access control during uploads.
- This change aligns with user expectations for file visibility and enhances the clarity of the upload process.
> [!Tip]

fix(code-viewer): set default visibility for uploaded files to 'public'

---

apps/web/index.html
apps/web/src/components/landing-page-partials/use-cases-gallery/data.ts

- Changed the Open Graph URL in the index.html file from the staging site to the production site, ensuring accurate sharing information.
- Updated the useCasesData array to reflect the production URL for a specific use case, maintaining consistency across the application.
- Ensured compliance with code style rules, including the use of single quotes for string literals.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-key …

fix(meta): update Open Graph URL to production site

---

apps/web/src/components/landing-page-partials/use-cases-gallery/data.ts

- Changed the URL in the useCasesData array for a specific use case, ensuring it points to the correct resource.
- Ensured compliance with code style rules, including the use of single quotes for string literals.
> [!Tip]
> Please review the …

fix(use-cases-gallery): update URL for a specific use case

---

packages/ai-workspace-common/src/components/canvas/common/helper-line/index.tsx
packages/ai-workspace-common/src/components/canvas/common/helper-line/util.ts
packages/ai-workspace-common/src/components/canvas/index.scss
packages/ai-workspace-common/src/components/canvas/index.tsx
packages/ai-workspace-common/src/components/canvas/nodes/shared/types.ts
packages/ai-workspace-common/src/hooks/canvas/use-node-operations.ts

feat: add helper lines when dragging nodes

---

packages/ai-workspace-common/src/components/canvas/node-preview/code-artifact.tsx
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

fix: skip update code artifact in readonly mode

---

apps/api/src/canvas/canvas.service.ts
apps/api/src/misc/misc.service.ts
apps/api/src/user/user.module.ts
apps/api/src/user/user.service.ts
packages/ai-workspace-common/src/components/settings/account-setting/index.tsx
packages/ai-workspace-common/src/hooks/use-upload-minimap.ts
packages/ai-workspace-common/src/requests/types.gen.ts
packages/openapi-schema/schema.yml
packages/openapi-schema/src/schemas.gen.ts
packages/openapi-schema/src/types.gen.ts

fix: proper static file binding for user avatars and canvas minimaps

---

packages/ai-workspace-common/src/context/canvas.tsx

fix(canvas): internal state conversion error for shared canvas

---

packages/ai-workspace-common/package.json
packages/ai-workspace-common/src/components/markdown/plugins/mermaid/render.tsx
pnpm-lock.yaml

feat(ai-workspace-common): upgrade mermaid version

---

packages/skill-template/src/scheduler/module/artifacts/prompt.ts
packages/skill-template/src/scheduler/module/common/format.ts
packages/skill-template/src/scheduler/module/common/personalization.ts

- Updated the Mermaid renderer version from 10.9.0 to 11.6.0 in both prompt and format documentation for consistency.
- Removed outdated instruction regarding explaining concepts to a 3-year-old in the personalization module to streamline guidance.
- Ensured compliance with code style rules, including the use of single quotes for string literals and performance optimizations.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using …

fix(artifacts): update Mermaid renderer version in documentation

---

packages/ai-workspace-common/src/components/canvas/node-preview/index.tsx
packages/ai-workspace-common/src/components/document/index.scss
packages/ai-workspace-common/src/components/document/index.tsx
packages/ai-workspace-common/src/stores/document.ts
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

1. Added document table of contents feature
2. Implemented automatic heading extraction and hierarchical numbering
3. Added scroll tracking to highlight current section
4. Enabled smooth navigation between document sections
5. Integrated with document maximized view
Resolves #669
| <img src="https://github.com/user-attachments/assets/e83e4738-a972-4293-8aaf-af2b1fca1e10" alt="Before" width="700"> | <img src="https://github.com/user-attachments/assets/a5732f82-1ab0-4ab0-8ac3-ea94214bfaea" alt="After" width="700"> |

feat(document): enhance document editor and node preview components

---

packages/ai-workspace-common/src/components/common/header-actions.tsx
packages/ai-workspace-common/src/components/project/canvas-menu/index.tsx
packages/ai-workspace-common/src/components/project/index.tsx
packages/ai-workspace-common/src/components/project/project-settings/index.tsx
packages/ai-workspace-common/src/components/project/source-menu/index.tsx
packages/ai-workspace-common/src/components/workspace/library-modal/index.tsx
packages/ai-workspace-common/src/components/workspace/project-list/index.tsx
packages/ai-workspace-common/src/hooks/canvas/use-node-size.ts
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

- Wrapped the exit button in a Tooltip for better user experience in HeaderActions.
- Refactored project canvas handling to fetch canvases dynamically based on projectId, improving navigation logic in Project component.
- Updated CanvasMenu to use ellipsis for text truncation, enhancing readability.
- Introduced LibraryModal in ProjectSettings for better project management.
- Replaced IconDelete with IconRemove in SourceItemActionDropdown for consistency.
- Enhanced ProjectList to manage library modal visibility directly, improving state management.
- Updated translations for new actions related to file management, enhancing localization support.
- Ensured compliance with Tailwind CSS styling and performance optimizations throughout the components.
Please include a summary of the change …

feat: enhance project components with improved UI and functionality

---

packages/ai-workspace-common/src/components/canvas/nodes/group.tsx
packages/ai-workspace-common/src/hooks/canvas/use-canvas-layout.ts

- Added onLayoutWithGroup function to handle layout for grouped nodes.
- Enhanced GroupNode component to utilize the new layout functionality.
- Improved node dimension handling with constants for default sizes.
- Ensured proper null checks and array validations for robust performance.
> [!Tip]
| …

refactor: integrate group layout functionality in use-canvas-layout hook

---

packages/ai-workspace-common/src/components/sider/layout.tsx

- Updated the View All button in the sidebar to include an icon for improved visual appeal and user experience.
- Adjusted button styling using Tailwind CSS for better hover effects and consistency.
- Ensured safe property access and maintained compliance with React performance optimizations.
> [!Tip]
| Before | …

refactor(sider): enhance View All button styling and interactivity

---

packages/ai-workspace-common/src/components/canvas/launchpad/chat-input.tsx

fix(#741): improve Enter‑key behavior for better UX  
================================================
This PR fixes the *“Unable to line break when slash (/) is present in the AI input box”* bug and refines key‑handling logic:
* **New behavior**
* **Send**: `Enter` **or** `Ctrl/⌘ + Enter`
* **Line break**: `Shift + Enter`
* **Bug fix**
* Previously, if a slash (`/`) appeared anywhere in the draft, `Enter` stopped inserting new lines.  
The logic now only treats `/` as a command trigger when it’s the **first** non‑whitespace character.
Motivation: predictable, IDE‑style shortcuts make it easier to craft multi‑line prompts without accidentally sending half‑finished text.  
Dependencies: none.
Fixes #741
---
---
| `Shift + Enter` ignored when `/` …

fix(#741): improve Enter key behavior for better UX

---

apps/api/.env.example
apps/api/src/common/redis.service.ts
apps/api/src/config/app.config.ts

- Added REDIS_USERNAME to the environment configuration for Redis.
- Updated RedisService and app.config to utilize the new username property.
- Ensured compliance with safe property access practices and React performance optimizations.
> [!Tip]

feat(api): add username configuration to Redis settings

---

apps/api/Dockerfile

chore(deploy): optimize docker image size

---

.gitpod.yml
README.md
README_CN.md

feat: deploy to gitpod

---

apps/api/src/modules/collab/collab.service.ts
packages/ai-workspace-common/src/components/canvas/launchpad/config-manager/index.tsx
packages/ai-workspace-common/src/components/canvas/nodes/image.tsx
packages/ai-workspace-common/src/components/skill/template-config-form-items/index.tsx
packages/ai-workspace-common/src/hooks/canvas/use-find-images.ts
packages/ai-workspace-common/src/requests/types.gen.ts
packages/i18n/src/en-US/skill-log.ts
packages/i18n/src/en-US/skill.ts
packages/i18n/src/zh-Hans/skill-log.ts
packages/i18n/src/zh-Hans/skill.ts
packages/openapi-schema/schema.yml
packages/openapi-schema/src/schemas.gen.ts
packages/openapi-schema/src/types.gen.ts
packages/skill-template/src/inventory.ts
packages/skill-template/src/skills/image-generation.ts
packages/skill-template/src/skills/index.ts

This PR introduces the **Image Generation** feature into the system.
**Main Changes:**
- Added `ImageGeneration` skill template (`packages/skill-template/src/skills/image-generation.ts`).
- Registered `ImageGeneration` skill in both `createSkillTemplateInventory` and `createSkillInventory`.
- Updated English (`en-US`) and Simplified Chinese (`zh-Hans`) i18n translation files to support image generation logs and UI texts.
- Modified the `ImageNode` component to safely fallback to empty strings for `imageUrl`.
- Improved `useFindImages` hook to ensure `imageUrl` and `storageKey` are always present in the returned metadata.
- Minor adjustments to `ConfigItem` components to support password input types.
**Motivation and Context:**
This feature allows users to generate images via AI models …

feat: add image generation skill

---

packages/ai-workspace-common/src/components/canvas/index.tsx

Fixed the exception where the query result was empty due to setting default values
Fixes #817

fix(canvas): invalid canvasId value when requesting slides data

---

apps/api/Dockerfile

fix(deploy): circular dependency with the wkhtmltopdf stage

---

apps/api/Dockerfile

fix: font issues for wkhtmltopdf

---

README.md
README_CN.md

Add one-click deploy on Sealos

---

packages/ai-workspace-common/src/components/document/index.tsx

- Added provider status check to determine loading state.
- Refactored loading condition to enhance clarity and maintainability.
> [!Tip]

fix(document): improve loading state handling in DocumentBody component

---

packages/ai-workspace-common/src/stores/action-result.ts

fix(canvas): increase maximum stored action results to avoid infinite data fetching loop

---

packages/ai-workspace-common/src/components/canvas/index.tsx
packages/ai-workspace-common/src/components/canvas/node-preview/code-artifact.tsx
packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/action-step.tsx
packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/index.tsx
packages/ai-workspace-common/src/components/canvas/nodes/code-artifact.tsx
packages/ai-workspace-common/src/components/document/collab-editor.tsx
packages/ai-workspace-common/src/components/document/index.tsx
packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-file.tsx
packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-image.tsx
packages/ai-workspace-common/src/components/markdown/plugins/artifact-thinking/render.tsx
packages/ai-workspace-common/src/context/canvas.tsx
packages/ai-workspace-common/src/context/document.tsx
packages/ai-workspace-common/src/hooks/canvas/use-update-action-result.ts
packages/ai-workspace-common/src/hooks/use-fetch-share-data.ts
packages/ai-workspace-common/src/requests/proxiedRequest.ts
packages/ai-workspace-common/src/utils/auth.ts
packages/ai-workspace-common/src/utils/sse-post.ts

- Updated various components to use optional chaining (?.) and nullish coalescing (??) for safer property access, preventing potential runtime errors.
- Ensured consistent handling of provider status checks and artifact statuses across multiple files.
- Improved code maintainability and readability by adhering to best practices for property access.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more …

fix: ensure safe property access throughout components

---

apps/api/package.json
apps/api/scripts/download-binaries.js

feat: download redis qdrant binary

---

.github/workflows/build-image.yml
apps/api/package.json
apps/api/src/scripts/sync-db-schema.ts
deploy/docker/docker-compose.yml
pnpm-lock.yaml

fix(deploy): prisma script and docker compose entrypoint issues

---

packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/model-selector.tsx
packages/ai-workspace-common/src/components/canvas/launchpad/context-manager/components/base-mark-context-selector/index.tsx
packages/ai-workspace-common/src/components/canvas/launchpad/context-manager/context-item.tsx
packages/ai-workspace-common/src/components/canvas/node-action-menu/index.tsx
packages/ai-workspace-common/src/components/canvas/nodes/memo/memo-editor.tsx
packages/ai-workspace-common/src/components/canvas/nodes/memo/memo.tsx
packages/ai-workspace-common/src/components/settings/model-config/index.tsx
packages/ai-workspace-common/src/hooks/canvas/use-add-to-context.ts
packages/ai-workspace-common/src/hooks/canvas/use-node-size.ts
packages/ai-workspace-common/src/utils/event-emitter/model.ts
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts
packages/utils/src/event-emitter/model.ts
packages/utils/src/index.ts

Fixes #847 
Fixes #787
> [!Tip]

fix(canvas): adjust memo style and model selector data fetching

---

apps/api/Dockerfile

fix(api): update main entry point in Dockerfile for consistency

---

.github/workflows/ci-docs.yml
.github/workflows/ci.yml
.github/workflows/deploy-docs.yml
.github/workflows/deploy-web-prod.yml
.github/workflows/deploy-web-staging.yml

- Combined the installation and build commands into a single step for both CI and deployment workflows to enhance efficiency and reduce redundancy.
- Updated working directory specification for deployment to align with the new structure.
> [!Tip]

chore(ci): streamline installation and build steps in workflows

---

.github/workflows/deploy-docs.yml
package.json

- Added path filter for 'docs/**' to the deploy-docs workflow, ensuring that documentation updates trigger the deployment process.
> [!Tip]

chore: update deploy-docs workflow to include documentation changes

---

apps/web/src/components/layout/index.tsx
apps/web/src/main.tsx
packages/ai-workspace-common/src/components/canvas-template/template-list.tsx
packages/ai-workspace-common/src/components/canvas/index.tsx
packages/ai-workspace-common/src/components/canvas/node-preview/resource.tsx
packages/ai-workspace-common/src/components/document/collab-editor.tsx
packages/ai-workspace-common/src/components/document/index.scss
packages/ai-workspace-common/src/components/search/data-list.tsx
packages/ai-workspace-common/src/components/search/home.tsx
packages/ai-workspace-common/src/components/search/index.scss
packages/ai-workspace-common/src/components/search/index.tsx
packages/ai-workspace-common/src/components/search/item.tsx

fix: style improvements in dark mode

---

packages/ai-workspace-common/src/modules/artifacts/code-runner/code-viewer.tsx
packages/ai-workspace-common/src/modules/artifacts/code-runner/monaco-editor/MonacoEditorComponent.tsx

Remove hardcoded background colors and add theme-responsive styling to the code viewer. Integrate Monaco editor with the application's theme system to properly display dark/light modes based on user preference.
> [!Tip]
> Please review the …

feat: implement dynamic theme support for code viewer

---

apps/api/src/modules/mcp-server/mcp-server.service.ts
packages/skill-template/src/index.ts
packages/skill-template/src/utils/index.ts

- Merged import statements in mcp-server.service.ts for cleaner code structure.
- Updated index.ts in skill-template to export additional modules for better accessibility.
> [!Tip]
> Please review the checklist below before submitting your …

fix(api): incorrect imports in mcp-server service

---

apps/api/src/modules/mcp-server/mcp-server.service.ts
packages/skill-template/src/skills/agent.ts

Reorganize imports, add proper type definitions for MCP tools, and enhance error handling during agent component initialization. Improve user identification logic and add better fallbacks when MCP servers are unavailable.
> [!Tip]
> Please …

refactor: improve MCP client initialization and type safety

---

packages/ai-workspace-common/src/modules/artifacts/code-runner/monaco-editor/MonacoEditorComponent.tsx

- Removed outdated CDN switching logic to simplify the component.
- Consolidated generation indicator handling to avoid unnecessary re-renders.
- Enhanced fallback editor handling for better user experience during loading errors.
- Ensured consistent use of Tailwind CSS for styling adjustments.
- Applied optional chaining and nullish coalescing for safer property access throughout the component.
> [!Tip]
> Please …

fix(MonacoEditorComponent): render hooks error

---

packages/skill-template/src/mcp/core/prompt.ts

Enhance the Refly-Orchestrator system prompt to prioritize MCP tool usage for specific query types. Add explicit conditions requiring tool use for real-time data, calculations, external state operations, and user-specific environments.
> [!Tip]
> [!IMPORTANT] …

Update MCP system prompt with stronger tool orchestration emphasis

---

packages/skill-template/src/skills/agent.ts

Enhance robustness by adding proper error handling when listing MCP servers and initializing connections. Provide fallbacks for failed responses and remove unnecessary error re-throw.
> [!Tip] …

fix: improve error handling in MCP server initialization

---

packages/ai-workspace-common/src/components/canvas/launchpad/config-manager/index.tsx
packages/ai-workspace-common/src/components/canvas/node-chat-panel/index.tsx
packages/ai-workspace-common/src/hooks/canvas/use-action-polling.ts
packages/ai-workspace-common/src/hooks/canvas/use-debounced-context-update.ts
packages/ai-workspace-common/src/hooks/canvas/use-find-thread-history.ts
packages/ai-workspace-common/src/stores/action-result.ts
packages/ai-workspace-common/src/stores/canvas.ts
packages/ai-workspace-common/src/stores/document.ts
packages/ai-workspace-common/src/stores/utils/storage-manager.ts

fix: local storage quota exceeded errors

---

apps/web/src/pages/code-share/index.tsx
apps/web/src/pages/document-share/index.tsx
apps/web/src/pages/page-share/index.tsx
apps/web/src/pages/pages/components/ArtifactRenderer.tsx
apps/web/src/pages/pages/components/EmptyContentPrompt.tsx
apps/web/src/pages/pages/components/ImageRenderer.tsx
apps/web/src/pages/pages/components/PageLayout.tsx
apps/web/src/pages/pages/components/PreviewMode.tsx
apps/web/src/pages/pages/components/SidebarMinimap.tsx
apps/web/src/pages/pages/components/SkillResponseRenderer.tsx
apps/web/src/pages/pages/index.tsx
apps/web/src/pages/pages/styles/preview-mode.css
packages/ai-workspace-common/src/components/canvas/front-page/index.tsx
packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/preview-chat-input.tsx
packages/ai-workspace-common/src/components/markdown/plugins/code/render.tsx
packages/ai-workspace-common/src/components/markdown/plugins/mermaid/render.tsx
packages/ai-workspace-common/src/components/markdown/styles/highlight.scss
packages/ai-workspace-common/src/components/markdown/styles/markdown.scss
packages/ai-workspace-common/src/components/sider/layout.tsx
packages/ai-workspace-common/src/components/subscription/hint.tsx
packages/ai-workspace-common/src/modules/artifacts/code-runner/monaco-editor/SimpleTextEditor.tsx

fix: dark mode style improvements

---

apps/api/src/modules/knowledge/parsers/pandoc.parser.ts

config: support docx  table

---

.gitignore
apps/api/src/modules/config/app.config.ts
apps/api/src/modules/provider/provider.service.ts
packages/ai-workspace-common/src/components/markdown/index.tsx
packages/observability/package.json
packages/observability/src/index.ts
packages/observability/src/langchain-callback.ts
packages/observability/src/langfuse-client.ts
packages/observability/src/langfuse-listener.ts
packages/observability/src/langfuse.service.ts
packages/observability/src/trace-manager.ts
packages/observability/src/types.ts
packages/observability/tsconfig.json
packages/providers/package.json
packages/providers/src/embeddings/index.ts
packages/providers/src/index.ts
packages/providers/src/llm/index.ts
packages/providers/src/monitoring/langfuse-wrapper.ts
packages/skill-template/src/mcp/core/prompt.ts
packages/skill-template/src/skills/agent.ts
pnpm-lock.yaml

feat: optimize MCP prompts and add langfuse integration

---

apps/api/package.json

- Modified the build script to copy generated files from src/generated to dist/generated for improved build process consistency.
> [!Tip]

fix(api): update build script to include generated files copy

---

packages/providers/src/embeddings/jina.ts

feat: jina embedding support input with more than 2048 bytes

---

apps/api/src/modules/config/app.config.ts
apps/api/src/modules/pilot/pilot-engine.ts
apps/api/src/modules/pilot/pilot.service.ts
apps/api/src/modules/pilot/prompt/index.ts
apps/api/src/modules/provider/provider.service.ts

feat: support global defaultModel configuration

---

packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

feat: update slogan in home page

---

packages/ai-workspace-common/src/components/canvas/launchpad/mcp-selector-panel/index.tsx

fix: mcp select count error

---

packages/ai-workspace-common/src/modules/artifacts/code-runner/render/html.tsx

fix: Clicking on the href tag in an html node does not lead to a redirection

---

.gitignore
apps/api/.gitignore
package.json
scripts/check-i18n-consistency.js

chore: add i18n translations checker

---

apps/api/src/modules/common/object-storage/backend/fs.ts
apps/api/src/modules/common/object-storage/backend/minio.ts

fix(api): handle empty data in putObject method

---

packages/ai-workspace-common/src/modules/artifacts/code-runner/render/react.tsx

- Updated the tsconfig property assignment to directly use tsConfig instead of wrapping it in an object.
- Improved code readability and maintainability by reducing unnecessary nesting.
> [!Tip]

fix(code-artifact): ReactCodeRunner crash

---

.github/workflows/upload-config.yml
config/mcp-catalog.json
scripts/upload-config.js

chore: add config upload for mcp catalog

---

packages/ai-workspace-common/src/components/canvas/launchpad/mcp-selector-panel/index.tsx
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

- Replaced the Settings icon with ChevronRight in the button for better visual indication of action.
- Adjusted button layout to include flex properties for improved alignment and spacing.
> [!Tip] …

fix(McpSelectorPanel): update button icons and enhance layout

---

packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx

- Updated connection filters to exclude 'skillResponse' type items from response context, improving data handling and preventing unnecessary connections.
> [!Tip]

fix(canvas): refine skill response connection filters

---

apps/api/src/modules/action/action.dto.ts

Added return outputUrl field

---

apps/api/src/modules/misc/misc.service.ts

Add support for mediaResult type in checkEntity method
> [!Tip]

fix(api): add support for mediaResult type in checkEntity method

---

packages/ai-workspace-common/src/components/canvas/front-page/action.tsx
packages/ai-workspace-common/src/components/canvas/front-page/chat-mode-selector.tsx
packages/ai-workspace-common/src/components/canvas/front-page/index.tsx
packages/ai-workspace-common/src/components/canvas/nodes/media/media-input.tsx
packages/ai-workspace-common/src/components/canvas/nodes/media/media-skill-response.tsx
packages/ai-workspace-common/src/components/canvas/nodes/media/mediaSkill.tsx
packages/ai-workspace-common/src/components/common/icon.tsx
packages/ai-workspace-common/src/events/nodeOperations.ts
packages/ai-workspace-common/src/hooks/canvas/use-create-canvas.ts
packages/ai-workspace-common/src/hooks/canvas/use-listen-node-events.ts
packages/ai-workspace-common/src/hooks/use-canvas-initial-actions.ts
packages/ai-workspace-common/src/stores/chat/index.ts
packages/ai-workspace-common/src/stores/front-page.ts
packages/i18n/src/en-US/ui.ts
packages/i18n/src/zh-Hans/ui.ts

feat: imageGeneration

---

packages/ai-workspace-common/src/components/canvas/front-page/action.tsx
packages/ai-workspace-common/src/components/canvas/front-page/index.tsx
packages/ai-workspace-common/src/components/canvas/launchpad/chat-panel.tsx
packages/ai-workspace-common/src/components/canvas/nodes/media/media-model-selector.tsx

- Integrated handleOpenSettingModal function to the Button for improved user interaction.
- Ensured proper usage of optional chaining for mediaModelList length check.
> [!Tip]
> Please review the checklist below before submitting your pull …

fix: add onClick handler to Button in MediaModelSelector component

---

config/provider-catalog.json
packages/ai-workspace-common/src/components/settings/model-providers/ProviderStore.tsx

- Removed duplicate LiteLLM provider entry and restructured its placement in the provider catalog.
- Updated ProviderStore to remove sorting of filtered providers, ensuring consistent output.
> [!Tip] …

refactor(provider-catalog): reorganize provider entry for LiteLLM

---

README.md

Add ClawCloud Run button to Readme

docs: add ClawCloud Run button

---

apps/api/src/modules/canvas/canvas-sync.service.ts
apps/api/src/modules/pages/pages.service.ts
packages/ai-workspace-common/src/components/canvas/top-toolbar/canvas-title.tsx
packages/ai-workspace-common/src/components/pilot/session-header.tsx
packages/ai-workspace-common/src/context/canvas.tsx
packages/canvas-common/src/constants.ts
packages/canvas-common/src/sync.test.ts
packages/canvas-common/src/sync.ts
packages/stores/src/stores/canvas.ts

fix: optimize canvas synchronization and version creation

---

apps/api/src/modules/workflow/workflow.module.ts
apps/api/src/modules/workflow/workflow.service.ts

- Included KnowledgeModule in the workflow module imports to enhance functionality.
- Ensured proper integration with existing modules while maintaining code clarity.
> [!Tip]
> Please review the checklist below before submitting your pull …

fix(workflow): add KnowledgeModule to workflow module

---

apps/api/src/modules/credit/credit.service.ts
apps/api/src/modules/workflow/workflow.module.ts
apps/api/src/modules/workflow/workflow.service.ts
packages/ai-workspace-common/src/components/canvas/front-page/action.tsx
packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/index.tsx
packages/canvas-common/src/types.ts

fix: adapt workflow for reading existing tool call usage
