refly-ai/refly

- packages/ai-workspace-common/src/components/canvas/launchpad/index.tsx
- Fix incorrect context state reset when input in launchpad
> [!Tip]
Before:
https://github.com/user-attachments/assets/48f6573e-fec3-4871-92c5-a2bb371cf32e
After:
https://github.com/user-attachments/assets/eb208813-0446-419c-8c26-bf35ad3f81fc
> fix(canvas): incorrect context state reset for launchpad input

- apps/api/src/config/app.config.ts
- Set storage quota to non-negative values to facilitate local deploy.
> [!Tip]
> fix(api): adjust storage quota default

- packages/ai-workspace-common/src/components/workspace/resource-list/index.tsx
- Implement dynamic favicon fetching for resources with URLs
- Add fallback icon rendering using SVG when favicon fails to load
- Use Google's favicon service for retrieving website icons
- Enhance resource card visual representation with website-specific icons
> [!Tip]
| ... …
> feat(workspace): Add website favicon support for resource cards

- packages/ai-workspace-common/src/components/canvas/nodes/memo/memo-editor.tsx
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
> feat(ui): Add preset colors for memo background color picker

- apps/api/src/skill/skill.service.ts
- packages/skill-template/src/scheduler/utils/queryProcessor.ts
- packages/skill-template/src/scheduler/utils/token.ts
- packages/skill-template/src/scheduler/utils/truncator.ts
Images in chat history will automatically be passed to the model, so users don't have to specify identical images for subsequent asks.
> [!Tip]
Note that no images are passed for the second question.
> feat: auto consumption of images in chat history

- apps/api/Dockerfile
- Install pandoc for different architectures (amd64 and arm64)
- Add gcompat library for compatibility
- Use wget to download and extract pandoc binaries
- Conditionally install based on target architecture
> feat(deploy): Add multi-arch pandoc installation in API Dockerfile

- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/components/canvas/layout-control/index.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-canvas-sync.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
> feat(canvas): undo and redo management for canvas

- packages/ai-workspace-common/src/components/canvas/nodes/memo/memo.tsx
- Add dragging state check to conditionally render memo node action buttons
- Integrate editor performance context to track dragging node
- Prevent action buttons from appearing while a node is being dragged
> [!Tip]
> Please review the …
> feat(canvas): Hide action buttons during node dragging

- packages/ai-workspace-common/src/components/canvas/canvas-toolbar/index.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/model-selector.tsx
- packages/ai-workspace-common/src/components/import-resource/index.scss
- packages/ai-workspace-common/src/components/import-resource/index.tsx
- packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-text.tsx
- packages/ai-workspace-common/src/components/settings/subscribe-modal/index.tsx
- packages/ai-workspace-common/src/modules/entity-selector/utils/fetcher.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
> feat(ai-workspace-common): change arco modal

- .github/workflows/e2e.yml
- package.json
- packages/ai-workspace-common/src/components/canvas/top-toolbar/index.tsx
- Remove unnecessary debounced canvas list refetching
- Directly update canvas title in useEffect
- Clean up unused imports and hooks
> [!Tip]
> fix(web): simplify canvas title update mechanism

- packages/ai-workspace-common/src/components/canvas/launchpad/config-manager/index.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/shared/types.ts
- packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/skill.tsx
- Extend skill and response nodes to support template configuration
- Add `tplConfig` to node metadata and types
- Implement config change handling in skill node
- Enhance config manager with optional form values change callback
> [!Tip]
> feat(canvas): support persisting and duplicating tplConfig for skill nodes

- .github/workflows/build-image.yml
- apps/api/src/canvas/canvas.service.ts
- packages/ai-workspace-common/src/components/document/index.tsx
- packages/ai-workspace-common/src/components/editor/core/extensions/updated-image.ts
- packages/ai-workspace-common/src/hooks/canvas/use-canvas-sync.ts
- packages/ai-workspace-common/src/hooks/canvas/use-patch-node-data.ts
- packages/ai-workspace-common/src/hooks/use-document-sync.ts
- Fix ydoc retrieval issues when canvas stateStorageKey is not present
- Fix markdown serialization error when image src is null
- Improve ydoc transaction handling when provider is not connected
> [!Tip]
> fix: alert issues

- apps/api/src/misc/misc.dto.ts
- cypress/e2e/canvas.cy.ts
- cypress/support/commands.ts
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/model-selector.tsx
- packages/ai-workspace-common/src/requests/types.gen.ts
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
- Extend ModelInfo type with optional isDefault property
- Implement model selection logic to prioritize default models
- Update OpenAPI schema and type generation to include isDefault flag
- Add helper function to select available models based on usage and default status
> [!Tip]
| ------ | ----- …
> feat(model): add isDefault flag to model selection and metadata

- apps/api/src/knowledge/knowledge.service.ts
- apps/api/src/misc/misc.controller.ts
- apps/api/src/misc/misc.service.ts
- packages/ai-workspace-common/src/hooks/use-download-file.ts
- packages/ai-workspace-common/src/hooks/use-export-canvas-as-image.ts
- Update static file endpoint to use JwtAuthGuard and handle CORS dynamically
- Modify file stream service to require authenticated user
- Improve canvas image export by converting images to base64 for better compatibility
- Add robust error handling for image conversion in export process
> [!Tip]
| <img width="599" alt="image" src="https://github.com/user-attachments/assets/1873b461-5249-4684-97c9-5d05c5acf116" /> | <img width="515" alt="image" …
> fix(api & canvas): missing image display when exporting canvas as image

- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-add-node.ts
- packages/ai-workspace-common/src/hooks/canvas/use-canvas-sync.ts
- packages/ai-workspace-common/src/hooks/canvas/use-set-node-data-by-entity.ts
- packages/ai-workspace-common/src/stores/context-panel.ts
- packages/ai-workspace-common/src/utils/map-context-items.ts
- Purge nested duplicate context when adding new nodes
- Automatically remove recursive `contextItems` data for existing canvases
- Add missing `runtimeConfig` for skill node preview
> [!Tip]
> fix: purge nested duplicate context for node data

- packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
- packages/ai-workspace-common/src/components/settings/account-setting/index.tsx
> feat(account): add loading state for avatar upload

- apps/api/src/misc/misc.service.ts
- Remove unnecessary file existence validation in misc service
- Simplify file processing logic by eliminating redundant error throw
> [!Tip]
> fix(api): remove redundant file existence check

- packages/ai-workspace-common/src/components/canvas/canvas-toolbar/index.tsx
- packages/ai-workspace-common/src/components/canvas/menu-popper/index.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-create-document.ts
- Modify node creation methods in CanvasToolbar and MenuPopper to include empty connections array
- Add optional parameters for node positioning and auto-selection
- Standardize node creation across different components
- Update useCreateDocument hook to match new node creation signature
> [!Tip] …
> feat(canvas): update node creation with additional parameters

- packages/i18n/src/en-US/ui.ts
- Update translation to remove dynamic link parameter
- Simplify share success message for code artifacts
> [!Tip]
> fix(i18n): remove dynamic link from code share success message

- apps/api/src/share/share.controller.ts
- apps/api/src/share/share.service.ts
- packages/ai-workspace-common/src/components/canvas/top-toolbar/share-settings.tsx
- packages/ai-workspace-common/src/requests/types.gen.ts
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
- Add checks to prevent duplicate share records for entities
- Implement update mechanism for existing share records
- Add detailed logging for share creation and update processes
- Modify share creation response to return full ShareRecord
- Improve null and optional checks in share creation methods
> [!Tip]
> feat(share): support updating existing share content

- packages/ai-workspace-common/src/components/canvas/group-action-menu/group-name.tsx
- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/group.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/index.ts
- packages/ai-workspace-common/src/components/canvas/nodes/shared/color-picker.tsx
- packages/ai-workspace-common/src/context/canvas.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-batch-nodes-selection/use-group-nodes.ts
- packages/ai-workspace-common/src/hooks/canvas/use-node-hover.ts
- Add `shareLoading` to canvas context for better loading state management
- Enable color picker for group nodes
- Set group nodes to have a lower z-index for better visual layering
- Adjust color picker styling with rounded corners
> [!Tip]
> …
> feat(canvas): improve loading and group node rendering

- apps/api/src/knowledge/knowledge.service.ts
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/action-container.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-create-canvas.ts
- packages/ai-workspace-common/src/hooks/canvas/use-create-document.ts
- Remove local YJS document initialization and persistence
- Add API-based document creation with loading state
- Update document creation hooks to use new API client
- Simplify document creation process by removing local sync steps
> [!Tip]
> refactor(canvas & document): adjust canvas and document creation process

- apps/api/src/subscription/subscription.service.ts
- cypress/e2e/canvas.cy.ts
- Remove unnecessary plan change tracking
- Streamline subscription update process
- Eliminate redundant usage meter refresh logic
> [!Tip]
> fix(api): remove auto subscription update logic

- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/document.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/image.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/memo/memo.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/resource.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/skill.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-node-size.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
- Add a warning message for drag actions in read-only mode to inform users of restrictions
- Update cursor styles for nodes in read-only mode to indicate non-interactivity
- Modify node components to accept and handle read-only state, ensuring consistent behavior across different node types
- Enhance internationalization support by adding relevant translations for read-only warnings
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issu …
> feat(canvas): implement read-only mode warnings and cursor adjustments

- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/components/canvas/top-toolbar/buttons.tsx
- packages/ai-workspace-common/src/components/canvas/top-toolbar/canvas-title.tsx
- packages/ai-workspace-common/src/components/canvas/top-toolbar/index.tsx
- packages/ai-workspace-common/src/context/canvas.tsx
- packages/ai-workspace-common/src/context/document.tsx
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
- Implement a modal to notify users of connection timeouts with retry options
- Track provider health status and update connection timeout state accordingly
- Remove deprecated WarningButton component and integrate its functionality into the canvas component
- Update translations for connection timeout messages in English and Chinese
- Set a force sync interval for improved connection management
> [!Tip]
| ...    | <img width="2142" alt="image" …
> fix(canvas): enhance connection timeout handling and UI feedback

- .github/workflows/deploy-web-prod.yml
- .github/workflows/deploy-web-staging.yml
- .github/workflows/e2e.yml
- apps/web/src/main.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-create-canvas.ts
- packages/ai-workspace-common/src/utils/env.ts
- packages/utils/src/env.ts
> fix: web crash issues and sentry configuration

- packages/ai-workspace-common/src/components/canvas-template/template-list.tsx
- packages/ai-workspace-common/src/components/workspace/canvas-list-modal/index.tsx
- packages/ai-workspace-common/src/components/workspace/document-list/index.tsx
- packages/ai-workspace-common/src/components/workspace/resource-list/index.tsx
- packages/ai-workspace-common/src/components/workspace/scroll-loading/index.tsx
- Replaced traditional loading mechanisms with InfiniteScroll in TemplateList, CanvasListModal, DocumentList, and ResourceList components to enhance user experience.
- Introduced Spinner and EndMessage components for better loading and end state representation.
- Utilized useMemo and useCallback hooks for performance optimization in rendering list items and handling load more functionality.
- Updated empty state handling to provide clearer user feedback when no data is available.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see …
> refactor(workspace): implement infinite scroll for various lists

- apps/api/src/subscription/subscription.service.ts
- Added the allow_promotion_codes flag to the subscription creation process, allowing users to utilize promotion codes during subscription sign-up.
- Ensured compliance with code style rules, including the use of single quotes for string literals.
> [!Tip]
> feat(api): enable promotion codes for subscription creation

- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/events/nodeOperations.ts
- packages/ai-workspace-common/src/hooks/use-create-code-artifact.ts
- Introduced a new event emitter for node operations, allowing components to listen for and respond to node addition events.
- Updated the Flow component to handle the 'addNode' event, ensuring nodes can be added dynamically based on emitted events.
- Refactored the useCreateCodeArtifact hook to emit the 'addNode' event instead of directly calling the addNode function, improving decoupling and maintainability.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linki …
> fix(canvas): out-of-context error for creating code artifacts

- apps/web/src/pages/document-share/index.tsx
- apps/web/src/pages/skill-response-share/index.tsx
- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/preview-chat-input.tsx
- packages/ai-workspace-common/src/components/markdown/plugins/artifact/render.tsx
- packages/ai-workspace-common/src/events/nodeOperations.ts
- packages/ai-workspace-common/src/hooks/canvas/use-listen-node-events.ts
- Eliminated the CanvasProvider wrapper from DocumentSharePage and SkillResponseSharePage for cleaner component structure.
- Updated layout and styling using Tailwind CSS to maintain visual consistency.
- Ensured proper handling of optional properties and array methods to prevent runtime errors.
> [!Tip]
| Before | …
> fix(canvas): decouple canvas context from shared document and skill responses to avoid missing context errors

- apps/api/src/skill/skill.service.ts
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/model-selector.tsx
- packages/ai-workspace-common/src/components/canvas/node-chat-panel/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/index.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/shared/types.ts
- packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-invoke-action.ts
- packages/ai-workspace-common/src/hooks/canvas/use-update-action-result.ts
- packages/ai-workspace-common/src/hooks/use-skill-error.ts
- packages/ai-workspace-common/src/requests/types.gen.ts
- packages/ai-workspace-common/src/utils/notification.ts
- packages/errors/src/errors.ts
- packages/errors/src/guess.ts
- packages/errors/src/index.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
- Introduced `guessModelProviderError` to improve error handling in the SkillService and related components.
- Updated error messaging in the SkillResponseNodePreview and SkillResponseNode components to display more informative error messages.
- Added `errors` property to ResponseNodeMeta type for better error tracking.
- Ensured compliance with code style rules, including the use of single quotes for string literals and performance optimizations.
> [!Tip]
| ------ | …
> fix(skill-response): refine skill invocation errors

- README_CN.md
Just fix README_CN to reflect correct path for .env.example
> fix(docs): update README_CN to reflect correct path for .env.example

- apps/api/src/share/share.service.ts
- apps/api/src/skill/skill.service.ts
- Updated duplicateSharedSkillResponse to accept an optional extra parameter for target entity and replaceEntityMap, improving flexibility.
- Utilized optional chaining and nullish coalescing for safer property access and default values.
- Ensured compliance with Tailwind CSS styling and performance optimizations throughout the service.
> [!Tip]
> Please review the checklist below before submitting your pull …
> fix(api): incorrect duplication of shared skill responses

- packages/i18n/src/zh-Hans/ui.ts
- Changed the delete confirmation message to specify "知识库" instead of "项目" for improved clarity in user interactions.
- Ensured compliance with translation standards and overall consistency in messaging.
> [!Tip]
> Please review the checklist …
> refactor: update delete confirmation message for knowledge base

- packages/ai-workspace-common/src/components/canvas/nodes/memo/memo.tsx
- packages/ai-workspace-common/src/components/project/add-sources/index.tsx
- packages/ai-workspace-common/src/components/search-quick-open-btn/index.tsx
- packages/ai-workspace-common/src/components/sider/layout.tsx
- packages/ai-workspace-common/src/components/workspace/project-list/index.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-create-canvas.ts
- packages/ai-workspace-common/src/hooks/use-handle-sider-data.ts
- Updated cursor logic in MemoNode to account for focus state.
- Added click handler to focus the editor in MemoNode.
- Refactored AddSourcesMemo to use useCallback for source and canvas tab definitions, improving performance.
- Introduced internal state for visibility in AddSourcesMemo to manage modal open state more effectively.
- Adjusted modal properties for better user experience.
- Ensured proper array handling and validation throughout the components.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-wit …
> refactor: enhance MemoNode and AddSourcesMemo components

- packages/ai-workspace-common/src/components/sider/layout.scss
- packages/ai-workspace-common/src/components/sider/layout.tsx
- Added new border and margin styles to adaptive submenu for improved layout.
- Replaced AiOutlineMenuUnfold with AiOutlineMenuFold for better icon representation in the sidebar.
- Adjusted margin and width properties for menu items to enhance visual consistency.
- Applied Tailwind CSS for consistent styling across components.
- Ensured safe property access and maintained compliance with React performance optimizations.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-i …
> refactor(sider): enhance layout styles and update icon representation

- apps/web/src/pages/canvas/index.tsx
- packages/ai-workspace-common/src/components/home-redirect/index.tsx
This PR removes the automatic navigation logic from the canvas page, giving users more control over their navigation flow. The change was made in`apps/web/src/pages/canvas/index.tsx` by removing the useEffect hook that previously handled automatic redirects.
- Free-form Canvas Interface
- I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- I ran`cd web && npx lint-staged` to appease the lint gods
> fix(web): remove auto redirect in home page

- packages/ai-workspace-common/src/components/canvas/launchpad/context-manager/context-item.tsx
Fix #767: Remove dotted border from preview context items
This change removes the dotted border styling previously applied to context items marked as 'preview' in the context panel.
**Motivation and Context:**
As reported in issue #767, the dotted border on preview context items was perceived as visually inconsistent or unnecessary, potentially causing visual clutter. Removing this specific border style improves the clarity and consistency of the context panel UI.
**Issue Fixed:** Fixes #767
**Dependencies:**
No new dependencies are required for this change.
| *(Please add a screenshot/video showing a preview context item with the dotted border)* | *(Please add a screenshot/video showing the same preview context item …
> #767 Remove the dotted border

- packages/ai-workspace-common/src/hooks/canvas/use-add-node.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
**Fixes #763**
This Pull Request introduces a limit on the number of nodes that can be added to a single canvas. Previously, there was no restriction, which could lead to canvases growing excessively large. Such large canvases result in significant data payloads during network transmission and storage, potentially causing performance degradation and Out-of-Memory (OOM) errors for clients.
To address this, a maximum limit of **{{MAX_NODES_PER_CANVAS}}** nodes per canvas has been implemented. The `useAddNode` hook now includes checks before adding a new node:
1.  If the current node count is already at or exceeds the limit ({{MAX_NODES_PER_CANVAS}}), the add operation is blocked, and an informative error message is displayed to the user.
2.  If adding a new node would cause the count to …
> feat(canvas): implement canvas node limit and add warnings

- packages/ai-workspace-common/src/components/canvas/nodes/image.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/shared/types.ts
- packages/ai-workspace-common/src/components/common/image-preview.tsx
Fixes #735
This pull request implements the functionality to optionally hide the border and title on Image Nodes within the canvas. This enhancement addresses issue #735, providing users with greater flexibility in customizing the appearance of image nodes for a cleaner or more integrated visual layout.
The changes include:
- Adding `showBorder` and `showTitle` optional properties to the `ImageNodeMeta` type.
- Modifying the `ImageNode` component to read these properties from metadata.
- Conditionally applying the border styles and rendering the `NodeHeader` (title) based on the `showBorder` and `showTitle` metadata properties respectively.
| *(Add screenshot showing an image node with border/title)*   | *(Add …
> feat(canvas): support displaying image nodes without border and title

- packages/skill-template/src/scheduler/module/commonQnA/prompt.ts
- packages/skill-template/src/scheduler/module/librarySearch/prompt.ts
- packages/skill-template/src/scheduler/module/webSearch/prompt.ts
- packages/skill-template/src/scheduler/utils/common-prompt.ts
Fix: Add current time to system prompts #732
This pull request introduces the current time information into the system prompts for various AI assistant functionalities. This enhancement allows the AI to have time-sensitive context during interactions, which can be beneficial for providing more relevant and accurate responses, especially for time-dependent queries. The `buildCurrentTimeInfo` function in `common-prompt.ts` now generates a string containing the current UTC and local times, which is then integrated into the system prompts of the Common QnA, Library Search, and Web Search modules.
| No current time information in system prompts. | Current UTC and local time are included in the system prompts. |
> feat(skill): add current time to system prompts

- packages/ai-workspace-common/src/components/canvas/slideshow/create-from-canvas.tsx
- packages/ai-workspace-common/src/components/canvas/slideshow/index.scss
- packages/ai-workspace-common/src/components/canvas/slideshow/new-slide.tsx
- packages/i18n/src/zh-Hans/ui.ts
- Updated the layout of CreatePageFromCanvas to improve responsiveness and visual structure.
- Added padding and adjusted height calculations in the associated SCSS for better content display.
- Simplified the NewSlide component structure by removing unnecessary wrapper divs.
- Ensured proper use of Tailwind CSS for styling consistency and improved user experience.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) …
> refactor(slideshow): enhance CreatePageFromCanvas layout and styling

- packages/ai-workspace-common/src/hooks/canvas/use-add-node.ts
- Updated the maximum number of nodes allowed in a canvas from 100 to 500.
- Adjusted the warning threshold from 90% to 98% of the maximum nodes to enhance user experience.
> [!Tip]
> feat(canvas): increase maximum nodes per canvas and adjust warning threshold

- packages/ai-workspace-common/src/components/canvas/launchpad/chat-input.tsx
- packages/i18n/src/en-US/skill.ts
- packages/i18n/src/zh-Hans/skill-log.ts
- packages/i18n/src/zh-Hans/skill.ts
This PR fixes a bug where the up and down arrow keys were not functioning correctly for cursor navigation within the chat input component, particularly with multi-line text (as reported in #784). The issue stemmed from the `AutoComplete` component intercepting arrow key events even when its dropdown was not active or intended for navigation.
The fix involves conditionally rendering the `AutoComplete` component only when the skill selector is explicitly triggered. To facilitate this and avoid accidental triggering, the keyboard shortcut to open the skill selector has been changed from `/` to `Ctrl+/` (or `Cmd+/` on macOS).
Additionally, the placeholder text in English and Chinese has been updated to reflect the new shortcut. A minor unrelated change updates a Chinese translation in …
> #784 fix up and down

- packages/ai-workspace-common/src/components/canvas/launchpad/chat-input.tsx
Fix issue with image pasting functionality in ChatInput component. Previously, users were unable to paste images into the chat input as the TextArea's onPaste event handler only prevented the default behavior without actually uploading the image. After fixing this initial issue, a secondary problem emerged where each paste operation would upload the same image twice. This PR addresses both issues by:
1. Properly configuring the TextArea components to use the handlePaste function
2. Removing the duplicate paste handler from the parent div to prevent double uploads
This ensures that images can be properly pasted into the chat input and are uploaded exactly once per paste operation.
| Unable to paste images into …
> fix paste error

- apps/api/src/utils/stream.ts
- apps/web/src/pages/pages/components/PageLayout.tsx
- apps/web/src/pages/pages/index.tsx
- packages/ai-workspace-common/src/components/canvas/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/index.tsx
- packages/ai-workspace-common/src/components/canvas/top-toolbar/buttons.tsx
- packages/i18n/src/en-US/ui.ts
> fix(web): hide slide button in shared canvases

- packages/ai-workspace-common/src/components/canvas/nodes/shared/action-buttons.tsx
- Reduced the safety margin from 20 to 5 to improve menu positioning logic.
- Added a condition to align the menu with the top of the viewport if its height exceeds available space, enhancing visibility and usability.
> [!Tip]
> Please review …
> fix(action-buttons): adjust safety margin for menu positioning

- apps/api/src/modules/subscription/subscription.service.ts
- Introduced consent_collection property with terms_of_service set to 'required' during subscription creation to enhance compliance and user consent management.
> [!Tip]
> feat(api): add consent collection to subscription creation

- apps/api/src/modules/share/share.service.ts
- packages/ai-workspace-common/src/requests/types.gen.ts
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
- Refactored duplicateSharedDocument, duplicateSharedResource, duplicateSharedCodeArtifact, duplicateSharedSkillResponse, and duplicateSharedCanvas methods to accept a DuplicateShareRequest parameter, allowing for projectId to be passed along.
- Updated related OpenAPI schema and types to include projectId in the DuplicateShareRequest.
- Ensured safe property access and consistent handling of parameters throughout the service methods.
> [!Tip]
| ... …
> fix(api): replace entities when duplicating skill responses nodes in canvases

- apps/api/src/register-aliases.ts
- apps/api/tsconfig.json
- packages/providers/tsconfig.json
- Updated tsconfig.json to include the providers package reference.
- Registered the providers package alias in register-aliases.ts for improved module resolution.
- Removed unused paths configuration from providers' tsconfig.json to streamline settings.
> [!Tip]
> fix(api): add providers package to tsconfig and register aliases

- packages/ai-workspace-common/src/components/canvas/empty-guide/templates-guide.tsx
- packages/ai-workspace-common/src/components/canvas/front-page/action.tsx
- packages/ai-workspace-common/src/components/canvas/front-page/index.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/model-selector.tsx
- packages/ai-workspace-common/src/components/sider/layout.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-create-canvas.ts
- packages/ai-workspace-common/src/hooks/use-canvas-initial-actions.ts
- packages/ai-workspace-common/src/modules/entity-selector/components/search-list/index.tsx
- Adjusted height of the TemplatesGuide button for improved visual consistency.
- Updated FrontPage to include a new canvas creation action with an icon for better user interaction.
- Refined ModelSelector to optimize icon size for better presentation.
- Enhanced NewCanvasItem click handling for clarity and consistency.
- Improved useCanvasInitialActions to manage connection status and pending actions effectively.
- Ensured compliance with code standards, including optional chaining and nullish coalescing.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see …
> feat(canvas): enhance component styling and functionality

- .gitpod.yml
- apps/api/src/modules/common/object-storage/backend/minio.ts
- apps/api/src/modules/common/qdrant.service.ts
- apps/api/src/modules/config/app.config.ts
- apps/api/src/modules/provider/provider.service.ts
- apps/api/src/utils/web-search/searxng.ts
- deploy/docker/docker-compose.elasticsearch.yml
- deploy/docker/docker-compose.middleware.yml
- deploy/docker/docker-compose.yml
- deploy/docker/searxng/settings.yml
- deploy/docker/searxng/uwsgi.ini
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/index.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/model-selector.tsx
- packages/ai-workspace-common/src/components/settings/model-config/model-form.tsx
- packages/ai-workspace-common/src/requests/types.gen.ts
- packages/errors/src/errors.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
- packages/providers/src/embeddings/index.ts
- packages/skill-template/src/scheduler/module/multiLingualSearch/locale.ts
- **Default support for searXNG container**​​: No API key is required to access online search, and the compatibility issue with language codes during searches has been fixed.
- ​​**CmdK search defaults to database search​​**: Elasticsearch (ES) has been removed, allowing deployment on a 1 CPU / 2 GB RAM machine.
- **​​Fix for vector database initialization**​​: The vector database is only initialized when an embedding model is configured and content is added to the knowledge base for the first time.
- ​​**Fix for object storage initialization error**​​: Resolved the issue where initialization errors prevented the system from starting.
- **​​Optimized model selector configuration prompts**​​: Improved the guidance for configuring the model selector.
- Gitpod deployment configuration has …
> feat: optimize self deploy with searxng and other improvements

- apps/api/Dockerfile
- apps/api/nodemon.json
- apps/api/package.json
- apps/api/tsconfig.json
> fix(api): revert swc build and correct npm script paths

- .github/workflows/ci-docs.yml
- .github/workflows/deploy-docs.yml
- docs/package.json
- Updated CI and deployment workflows to split the installation and build commands into distinct steps for clarity and maintainability.
- Specified working directory for installation and build steps to ensure proper execution context.
- Added "name" and "private" fields to the package.json for better project identification.
> [!Tip]
> chore(ci): add --ignore-workspace flag to docs action

- apps/web/src/components/landing-page-partials/artifact-gallery/index.tsx
- apps/web/src/main.tsx
- apps/web/src/routes/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-action-menu/index.tsx
- packages/ai-workspace-common/src/components/document/index.tsx
- packages/ai-workspace-common/src/components/import-resource/index.scss
- packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-file.tsx
- packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-image.tsx
- packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-text.tsx
- packages/ai-workspace-common/src/components/import-resource/intergrations/import-from-weblink.tsx
- packages/ai-workspace-common/src/hooks/use-forced-light-mode.ts
- packages/ai-workspace-common/src/modules/multilingual-search/components/action-menu.scss
- packages/ai-workspace-common/src/modules/multilingual-search/components/action-menu.tsx
- packages/ai-workspace-common/src/stores/import-resource.ts
- packages/ai-workspace-common/src/stores/theme.ts
- Added support for forced light mode in the theme store and updated related components to utilize this feature.
- Refactored theme application logic to consider forced light mode when determining the current theme.
- Enhanced the App component to conditionally apply dark mode based on user preferences and forced settings.
- Cleaned up styling in the ArtifactGallery component to ensure consistency with Tailwind CSS.
- Ensured proper use of optional chaining and nullish coalescing for safer property access throughout the codebase.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, …
> feat(theme): implement forced light mode and improve theme handling

- apps/web/src/pages/pages/components/ResourceRenderer.tsx
- packages/ai-workspace-common/src/components/canvas/empty-guide/templates-guide.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/context-manager/components/chat-history-preview.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/action-container.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/action-step.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/group.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/shared/reasoning-content-preview.tsx
- packages/ai-workspace-common/src/components/import-resource/index.scss
- packages/ai-workspace-common/src/components/markdown/plugins/artifact/render.tsx
- packages/ai-workspace-common/src/components/markdown/plugins/link/render.tsx
- packages/ai-workspace-common/src/components/project/canvas-menu/index.tsx
- packages/ai-workspace-common/src/components/project/project-directory/index.scss
- packages/ai-workspace-common/src/components/project/source-menu/index.tsx
- packages/ai-workspace-common/src/components/source-list/index.tsx
- packages/ai-workspace-common/src/components/source-list/source-list-modal/index.scss
- packages/ai-workspace-common/src/components/source-list/source-list-modal/index.tsx
- packages/ai-workspace-common/src/components/translation-wrapper/index.tsx
- packages/ai-workspace-common/src/modules/multilingual-search/components/search-results.scss
- packages/ai-workspace-common/src/modules/multilingual-search/components/search-results.tsx
- Updated styles in ResourceRenderer, TemplatesGuide, and ChatHistoryPreview components to improve dark mode visibility.
- Added dark mode classes to various elements for better contrast and readability.
- Ensured consistent use of Tailwind CSS for styling adjustments.
- Applied optional chaining and nullish coalescing for safer property access throughout the components.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-ke …
> fix: enhance dark mode support across various components

- packages/ai-workspace-common/src/components/canvas/launchpad/chat-panel.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/recommend-questions-panel/index.tsx
- packages/ai-workspace-common/src/components/document/index.tsx
- packages/ai-workspace-common/src/modules/multilingual-search/components/action-menu.tsx
- Updated border styles in ChatPanel and RecommendQuestionsPanel components to improve dark mode visibility.
- Ensured consistent use of Tailwind CSS for styling adjustments across components.
- Applied optional chaining and nullish coalescing for safer property access throughout the components.
> [!Tip]
| Before | …
> fix: enhance dark mode styling in chat and recommend questions panels

- apps/api/src/modules/mcp-server/mcp-server.service.ts
- apps/api/src/modules/skill/skill.service.ts
- packages/ai-workspace-common/src/components/markdown/plugins/index.ts
- packages/ai-workspace-common/src/components/markdown/plugins/mcp-call/index.ts
- packages/ai-workspace-common/src/components/markdown/plugins/mcp-call/rehypePlugin.ts
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerBatchImport.tsx
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerForm.tsx
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerList.tsx
- packages/skill-template/src/mcp/core/prompt.ts
- packages/skill-template/src/skills/agent.ts
Enhance agent component caching by checking MCP server list changes before reusing cached components. Add proper cleanup on initialization errors and implement user-specific disposal. Also modify skill service to fallback to commonQnA instead of throwing an error when a skill is not found.
> [!Tip]
| Before | After …
> fix: improve agent skill component caching and fallback handling

- apps/api/prisma/schema.prisma
- apps/api/src/modules/mcp-server/mcp-server.service.ts
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerBatchImport.tsx
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerForm.tsx
Update schema to enforce unique server names per user instead of globally. Modify server service to properly scope queries by user ID when finding, creating, and updating MCP servers.
> [!Tip] …
> feat: make MCP server names unique per user

- packages/ai-workspace-common/src/components/markdown/index.tsx
- packages/ai-workspace-common/src/components/markdown/plugins/mcp-call/rehypePlugin.ts
- packages/ai-workspace-common/src/components/markdown/plugins/mcp-call/render.tsx
Remove remark-gfm dependency and enhance image handling in MCP call rehype plugin to support both base64 and HTTP/HTTPS image URLs with proper regex pattern matching and extraction.
> [!Tip] …
> feat(markdown): add HTTP image URL support in MCP call plugin

- packages/ai-workspace-common/src/components/canvas/constants.ts
- packages/ai-workspace-common/src/components/canvas/index.scss
- packages/ai-workspace-common/src/components/canvas/top-toolbar/canvas-title.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-edge-operations.ts
- Updated edge styles to support dark mode by integrating theme context.
- Modified `getEdgeStyles` function to accept dark mode parameter.
- Improved styling in `CanvasTitle` component for better dark mode support.
- Added transparent background for attribution in canvas styles.
> [!Tip]
> feat(canvas): enhance edge styles in dark mode for canvas components

- apps/web/src/main.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/index.tsx
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerList.tsx
- packages/ai-workspace-common/src/modules/artifacts/code-runner/monaco-editor/monacoPreloader.ts
Add Monaco Editor preloader utility that attempts to load from multiple CDNs with fallbacks. Integrate preloading in NodePreviewContainer and McpServerList components to improve initial load times for code editing features.
> [!Tip]
> Please …
> feat: implement Monaco Editor preloading for better performance

- packages/ai-workspace-common/src/components/markdown/plugins/mcp-call/rehypePlugin.ts
- packages/ai-workspace-common/src/components/markdown/plugins/mcp-call/render.tsx
Enhance the markdown plugin to detect and process audio URLs in tool call results, supporting formats like mp3, wav, ogg, flac, m4a, and aac. This implementation follows the same pattern as image URL handling, extracting audio URLs from results and setting appropriate data attributes.
> [!Tip]
| …
> Add audio URL detection and processing in markdown plugins

- packages/ai-workspace-common/src/components/canvas/launchpad/chat-actions/index.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/chat-panel.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/index.tsx
- packages/ai-workspace-common/src/components/canvas/launchpad/mcp-selector-panel/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-chat-panel/index.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/edit-chat-input.tsx
- packages/ai-workspace-common/src/components/canvas/node-preview/skill.tsx
Move MCP selector panel state management from global launchpad store to local useState in ChatPanel component for better encapsulation
> [!Tip]
> refactor: move MCP selector panel state to local component level

- apps/extension/src/components/content-selector/hooks/use-content-selector.tsx
- apps/extension/src/entrypoints/background/events/activated.ts
- apps/extension/src/entrypoints/background/events/detached.ts
- apps/extension/src/entrypoints/background/events/ports.ts
- apps/extension/src/entrypoints/contentSelector-csui.content/index.tsx
- apps/extension/src/entrypoints/floatingSphere-csui.content/App.tsx
- apps/extension/src/entrypoints/floatingSphere-csui.content/index.tsx
- apps/extension/src/entrypoints/utils-csui.content/index.tsx
- apps/extension/src/hooks/use-get-user-settings.ts
- apps/extension/src/hooks/use-storage.ts
- apps/extension/src/modules/toggle-copilot/hooks/use-toggle-copilot.ts
- apps/extension/src/utils/logger.ts
This PR implements a development-only logging system for the Refly Chrome extension to eliminate console spam in production while maintaining debugging capabilities during development.
Fixes #941 
| https://screen.studio/share/x1IkbtXH | https://screen.studio/share/XcXfWX0I   |
> feat(extension): implement development-only logger with debug toggle

- packages/ai-workspace-common/src/components/canvas/launchpad/mcp-selector-panel/index.tsx
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerList.tsx
Add sessionId dependency to MCP server fetch and display server URL or command as description when no description is available
> [!Tip]
> fix(mcp-selector): Add session validation and improve server display

- packages/ai-workspace-common/src/components/canvas/launchpad/mcp-selector-panel/index.tsx
- packages/ai-workspace-common/src/components/settings/mcp-server/McpServerList.tsx
Remove dependency on sessionId for fetching MCP servers in both the selector panel and server list components. Added debug logging to help troubleshoot server fetching behavior.
> [!Tip]
> Please review the checklist below before submitting …
> fix: remove sessionId requirement for MCP server fetching

- apps/web/src/main.tsx
Add dark mode style for messages and notifications, resolves #971 
| ![image](https://github.com/user-attachments/assets/4cf202a2-a24f-4315-9a7e-11c31aab9c66)   | ![image](https://github.com/user-attachments/assets/631a8928-8d2f-4a3f-af13-2eee4a5f8fa2) |
> fix: dark mode for messages and notifications

- apps/api/src/modules/skill/skill-invoker.service.ts
- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/index.tsx
- packages/ai-workspace-common/src/components/canvas/nodes/index.ts
- packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
- packages/ai-workspace-common/src/components/markdown/styles/markdown.scss
- packages/ai-workspace-common/src/hooks/canvas/use-action-polling.ts
- packages/ai-workspace-common/src/hooks/canvas/use-invoke-action.ts
- packages/ai-workspace-common/src/hooks/use-skill-error.ts
- packages/ai-workspace-common/src/modules/entity-selector/components/search-list/index.tsx
- packages/ai-workspace-common/src/stores/action-result.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
- packages/openapi-schema/package.json
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
Skills are now executed on server, loosely decoupled with SSE connection. When the browser is refreshed or closed during the process, the skill response can still be generated and retrieved.
> [!Tip]
> feat: support full skill execution on server

- packages/ai-workspace-common/src/components/editor/extensions/Table/menus/TableColumn/utils.ts
- packages/ai-workspace-common/src/components/editor/extensions/Table/menus/TableRow/utils.ts
- Enhanced null checks for view, editor initialization, and node existence to prevent runtime errors.
- Wrapped logic in try-catch blocks to handle potential exceptions gracefully.
- Ensured proper querying of grip elements in both column and row utilities for better reliability.
> [!Tip]
> fix(editor): improve error handling and validation in table grip selection utilities

- packages/ai-workspace-common/src/components/canvas/node-preview/skill-response/index.tsx
- Moved the isPending and errDescription logic inside the component to improve readability.
- Utilized useMemo for errDescription to optimize performance.
- Ensured consistent handling of loading and result states.
> [!Tip]
> fix(web): incorrect hook placement in SkillResponseNodePreviewComponent

- packages/skill-template/src/skills/agent.ts
Simplifies the Agent class by removing unused code for processing and truncating tool outputs, including constants and helper methods. Also removes an unused RunnableConfig import.
> [!Tip]
> Please review the checklist below before submitting …
> Remove tool output processing logic from Agent class

- apps/web/src/styles/style.css
- packages/ai-workspace-common/src/components/settings/subscribe-modal/index.scss
- packages/ai-workspace-common/src/components/settings/subscribe-modal/priceContent.tsx
- packages/ai-workspace-common/src/styles/style.css
- Added line-height of 1.5 to html and body elements in both web and common stylesheets for improved readability.
- Removed unnecessary font-weight and period styles from the subscribe modal's SCSS for cleaner code.
- Adjusted text color in priceContent component for better consistency with design.
> [!Tip]
| Before …
> style: update line-height for html and body elements in CSS files

- apps/api/nodemon.json
- apps/api/src/modules/internal-mcp/internal-mcp.module.ts
- apps/api/src/modules/internal-mcp/internal-mcp.service.ts
- apps/api/src/modules/internal-mcp/tools/mcp-server.tools.ts
- apps/api/src/modules/internal-mcp/tools/search.tools.ts
- apps/api/src/modules/pilot/pilot.dto.ts
- apps/api/src/modules/pilot/pilot.module.ts
- apps/api/src/modules/pilot/pilot.service.ts
- apps/api/src/modules/provider/provider.service.ts
- apps/api/src/modules/skill/skill-engine.service.ts
- apps/api/src/modules/skill/skill-invoker.service.ts
- apps/api/src/modules/skill/skill.processor.ts
- apps/api/tsconfig.json
- apps/desktop/nodemon.json
- apps/desktop/package.json
- apps/desktop/src/electron-env.d.ts
- apps/desktop/tsconfig.json
- packages/utils/src/brand.ts
- pnpm-lock.yaml
- Changed import paths in multiple modules to relative paths for consistency.
- Updated nodemon configurations for both API and desktop applications to improve build and execution processes.
- Added composite option in tsconfig for better project structure.
- Updated package.json scripts to include tsc-alias for better path resolution.
> [!Tip]
> Please review the checklist below before submitting your pull …
> refactor: update module imports and nodemon configurations

- packages/ai-workspace-common/src/components/canvas/nodes/skill-response.tsx
- packages/ai-workspace-common/src/hooks/canvas/use-action-polling.ts
- packages/ai-workspace-common/src/hooks/canvas/use-invoke-action.ts
- packages/ai-workspace-common/src/stores/action-result.ts
- Enhanced polling logic to prevent unnecessary updates for finished or failed results.
- Added timeout handling to manage race conditions during reruns.
- Updated action result store to prevent overriding final states with intermediate states.
- Improved cleanup of pending updates in the invoke action hook.
> [!Tip]
Please check the areas this PR …
> feat(canvas): improve skill response handling and polling logic

- docs/community-version/self-deploy/index.md
- docs/zh/community-version/self-deploy/index.md
- docs/zh/community-version/self-deploy/local-quick-start.md
- Changed relative links from '../configuration.md' to './configuration.md' for consistency in both English and Chinese documentation.
- Updated troubleshooting link in the Chinese local quick start guide for accurate navigation.
> [!Tip]
> docs: fix broken links to configuration guide in self-deploy documentation

- config/provider-catalog.json
- packages/ai-workspace-common/src/components/settings/model-config/index.tsx
- packages/ai-workspace-common/src/requests/types.gen.ts
- packages/i18n/src/en-US/ui.ts
- packages/i18n/src/zh-Hans/ui.ts
- packages/openapi-schema/schema.yml
- packages/openapi-schema/src/schemas.gen.ts
- packages/openapi-schema/src/types.gen.ts
- packages/utils/src/provider.ts
- Added new media generation providers: Replicate and FAL, with relevant details in the provider catalog.
- Updated ModelConfig component to manage media generation models, including state management and rendering.
- Introduced tabbed interface for model categories, including a dedicated tab for media generation.
- Enhanced UI with search functionality and add model button for media generation models.
- Added translations for media generation features in English and Chinese.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see …
> Enhance media generation support in model configuration

- packages/ai-workspace-common/src/components/settings/model-config/model-form.tsx
- Updated the ModelFormModal component to use optional chaining when accessing the media configuration array, preventing potential runtime errors when the providerKey is not found.
- This change enhances the robustness of the component by ensuring it handles undefined values gracefully.
> [!Tip]
| …
> fix: ensure safe access to media configuration in ModelFormModal

- packages/web-core/src/components/landing-page-partials/Header.tsx
- packages/web-core/src/pages/home-new/index.tsx
…andling
- Deleted the 'test' page option from the header dropdown and removed associated navigation logic.
- Simplified pathname handling in the useEffect to set the default value based on the current path.
> [!Tip]
> Please review the …
> fix: remove variable extraction test page
